#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BarcodeScannerDemo.Resource", IsApplication=true)]

namespace BarcodeScannerDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060004
			public const int entries_list_camera_frame_sizes = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int entries_list_encodings = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int entries_list_fps_limit = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int entries_list_languages = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int entries_list_recognition_mode = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int entryvalues_list_camera_frame_sizes = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int entryvalues_list_encodings = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int entryvalues_list_fps_limit = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int entryvalues_list_languages = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int entryvalues_list_recognition_mode = 2131099649;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int buttonPadding = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int drawingFontSize = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int fontSize = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int textViewPadding = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int titleFontSize = 2131165187;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090006
			public const int aboutButton = 2131296262;
			
			// aapt resource value: 0x7f09000b
			public const int clearHistoryButton = 2131296267;
			
			// aapt resource value: 0x7f09000e
			public const int contentFrame = 2131296270;
			
			// aapt resource value: 0x7f090009
			public const int flashlightButton = 2131296265;
			
			// aapt resource value: 0x7f090007
			public const int helpInfoTextView = 2131296263;
			
			// aapt resource value: 0x7f09000a
			public const int historyButton = 2131296266;
			
			// aapt resource value: 0x7f09000d
			public const int regocnizedBarcodeTextView = 2131296269;
			
			// aapt resource value: 0x7f090008
			public const int rightButtonsLayout = 2131296264;
			
			// aapt resource value: 0x7f090005
			public const int settingsButton = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int settingsLayout = 2131296260;
			
			// aapt resource value: 0x7f09000c
			public const int textViewLayout = 2131296268;
			
			// aapt resource value: 0x7f090002
			public const int titleIcon = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int titleLayout = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int titleTextView = 2131296259;
			
			// aapt resource value: 0x7f090000
			public const int titleWithHelpInfoLayout = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int barcode_reader_fragment_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int clear_history_disabled = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int clear_history_enabled = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int flash_off = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int flash_on = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int help = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int history = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int settings = 2130837511;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int barcode_recognized_sound = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080006
			public const int about_message = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int app_name = 2131230720;
			
			// aapt resource value: 0x7f080046
			public const int barcode_category_preference = 2131230790;
			
			// aapt resource value: 0x7f080031
			public const int barcode_found_preferences = 2131230769;
			
			// aapt resource value: 0x7f080060
			public const int barcodes_1D_preferences = 2131230816;
			
			// aapt resource value: 0x7f080047
			public const int barcodes_2D_preferences = 2131230791;
			
			// aapt resource value: 0x7f080092
			public const int barcodes_postal_1D_preferences = 2131230866;
			
			// aapt resource value: 0x7f08001c
			public const int barcodes_recognized_message = 2131230748;
			
			// aapt resource value: 0x7f080055
			public const int barcodes_stacked_GS1_preferences = 2131230805;
			
			// aapt resource value: 0x7f08002a
			public const int camera_preferences = 2131230762;
			
			// aapt resource value: 0x7f08000a
			public const int cell_size_message = 2131230730;
			
			// aapt resource value: 0x7f080024
			public const int click_for_detailed_info_message = 2131230756;
			
			// aapt resource value: 0x7f080004
			public const int copy_value_button = 2131230724;
			
			// aapt resource value: 0x7f080015
			public const int data_layers_message = 2131230741;
			
			// aapt resource value: 0x7f080030
			public const int dialog_title_list_camera_frame_sizes = 2131230768;
			
			// aapt resource value: 0x7f080038
			public const int dialog_title_list_encodings = 2131230776;
			
			// aapt resource value: 0x7f080043
			public const int dialog_title_list_fps_limit = 2131230787;
			
			// aapt resource value: 0x7f080029
			public const int dialog_title_list_languages = 2131230761;
			
			// aapt resource value: 0x7f08003c
			public const int dialog_title_list_recognition_mode = 2131230780;
			
			// aapt resource value: 0x7f080016
			public const int encoding_mode_message = 2131230742;
			
			// aapt resource value: 0x7f080014
			public const int error_correction_data_message = 2131230740;
			
			// aapt resource value: 0x7f080010
			public const int error_correction_level_message = 2131230736;
			
			// aapt resource value: 0x7f080022
			public const int fps_message = 2131230754;
			
			// aapt resource value: 0x7f080023
			public const int frame_scan_time_message = 2131230755;
			
			// aapt resource value: 0x7f08001e
			public const int help_info_barcode_recognized_message = 2131230750;
			
			// aapt resource value: 0x7f08001d
			public const int help_info_message = 2131230749;
			
			// aapt resource value: 0x7f080001
			public const int history_title = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int language_change_message = 2131230727;
			
			// aapt resource value: 0x7f080019
			public const int linkage_flag_message = 2131230745;
			
			// aapt resource value: 0x7f080009
			public const int matrix_size_message = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int metadata_message = 2131230728;
			
			// aapt resource value: 0x7f08000b
			public const int mirrored_message = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int narrow_bar_count_message = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int narrow_bar_size_message = 2131230733;
			
			// aapt resource value: 0x7f080003
			public const int ok_button = 2131230723;
			
			// aapt resource value: 0x7f080039
			public const int recognition_preferences = 2131230777;
			
			// aapt resource value: 0x7f08001b
			public const int recognition_quality_message = 2131230747;
			
			// aapt resource value: 0x7f08000f
			public const int reconstructed_message = 2131230735;
			
			// aapt resource value: 0x7f080011
			public const int rows_count_message = 2131230737;
			
			// aapt resource value: 0x7f08001f
			public const int scan_mode_auto_message = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int scan_mode_treshold_auto_message = 2131230752;
			
			// aapt resource value: 0x7f080021
			public const int scan_mode_treshold_message = 2131230753;
			
			// aapt resource value: 0x7f080017
			public const int segments_count_message = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int segments_in_row_message = 2131230744;
			
			// aapt resource value: 0x7f080044
			public const int settings_management_category_preference = 2131230788;
			
			// aapt resource value: 0x7f080002
			public const int settings_title = 2131230722;
			
			// aapt resource value: 0x7f080065
			public const int summary_checkbox_1D_barcodes_Code128 = 2131230821;
			
			// aapt resource value: 0x7f080068
			public const int summary_checkbox_1D_barcodes_Code39 = 2131230824;
			
			// aapt resource value: 0x7f08006e
			public const int summary_checkbox_1D_barcodes_DHLAWB = 2131230830;
			
			// aapt resource value: 0x7f080072
			public const int summary_checkbox_1D_barcodes_EAN13 = 2131230834;
			
			// aapt resource value: 0x7f080070
			public const int summary_checkbox_1D_barcodes_EAN8 = 2131230832;
			
			// aapt resource value: 0x7f08007b
			public const int summary_checkbox_1D_barcodes_OPC = 2131230843;
			
			// aapt resource value: 0x7f080080
			public const int summary_checkbox_1D_barcodes_PZN = 2131230848;
			
			// aapt resource value: 0x7f08007d
			public const int summary_checkbox_1D_barcodes_PatchCode = 2131230845;
			
			// aapt resource value: 0x7f080088
			public const int summary_checkbox_1D_barcodes_Standard2of5 = 2131230856;
			
			// aapt resource value: 0x7f08008c
			public const int summary_checkbox_1D_barcodes_UPCA = 2131230860;
			
			// aapt resource value: 0x7f08008e
			public const int summary_checkbox_1D_barcodes_UPCE = 2131230862;
			
			// aapt resource value: 0x7f080091
			public const int summary_checkbox_1D_barcodes_VIN = 2131230865;
			
			// aapt resource value: 0x7f080049
			public const int summary_checkbox_2D_barcodes_Aztec = 2131230793;
			
			// aapt resource value: 0x7f08004b
			public const int summary_checkbox_2D_barcodes_DataMatrix = 2131230795;
			
			// aapt resource value: 0x7f08004e
			public const int summary_checkbox_2D_barcodes_PDF417 = 2131230798;
			
			// aapt resource value: 0x7f080052
			public const int summary_checkbox_2D_barcodes_QR = 2131230802;
			
			// aapt resource value: 0x7f08005a
			public const int summary_checkbox_GS1_barcodes_GS1_128 = 2131230810;
			
			// aapt resource value: 0x7f08003e
			public const int summary_checkbox_invert_image = 2131230782;
			
			// aapt resource value: 0x7f080094
			public const int summary_checkbox_postal_1D_AustralianPost = 2131230868;
			
			// aapt resource value: 0x7f080096
			public const int summary_checkbox_postal_1D_DutchKIX = 2131230870;
			
			// aapt resource value: 0x7f08009e
			public const int summary_checkbox_postal_1D_IntelligentMail = 2131230878;
			
			// aapt resource value: 0x7f0800a0
			public const int summary_checkbox_postal_1D_Mailmark4C = 2131230880;
			
			// aapt resource value: 0x7f0800a2
			public const int summary_checkbox_postal_1D_Mailmark4L = 2131230882;
			
			// aapt resource value: 0x7f08009c
			public const int summary_checkbox_postal_1D_Planet = 2131230876;
			
			// aapt resource value: 0x7f08009a
			public const int summary_checkbox_postal_1D_Postnet = 2131230874;
			
			// aapt resource value: 0x7f080098
			public const int summary_checkbox_postal_1D_RoyalMail = 2131230872;
			
			// aapt resource value: 0x7f080040
			public const int summary_checkbox_reconstruct_structured_append_barcodes = 2131230784;
			
			// aapt resource value: 0x7f080033
			public const int summary_checkbox_stop_scan = 2131230771;
			
			// aapt resource value: 0x7f080026
			public const int summary_history_empty_message = 2131230758;
			
			// aapt resource value: 0x7f08002f
			public const int summary_list_camera_frame_sizes = 2131230767;
			
			// aapt resource value: 0x7f080042
			public const int summary_list_fps_limit = 2131230786;
			
			// aapt resource value: 0x7f08003b
			public const int summary_list_recognition_mode = 2131230779;
			
			// aapt resource value: 0x7f08000e
			public const int symbol_component_count_message = 2131230734;
			
			// aapt resource value: 0x7f080012
			public const int symbol_type_message = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int symbol_version_message = 2131230739;
			
			// aapt resource value: 0x7f080063
			public const int title_checkbox_1D_Code16K = 2131230819;
			
			// aapt resource value: 0x7f080084
			public const int title_checkbox_1D_RSS14_stacked = 2131230852;
			
			// aapt resource value: 0x7f080085
			public const int title_checkbox_1D_RSSExpanded_stacked = 2131230853;
			
			// aapt resource value: 0x7f080061
			public const int title_checkbox_1D_barcodes_Codabar = 2131230817;
			
			// aapt resource value: 0x7f080062
			public const int title_checkbox_1D_barcodes_Code11 = 2131230818;
			
			// aapt resource value: 0x7f080064
			public const int title_checkbox_1D_barcodes_Code128 = 2131230820;
			
			// aapt resource value: 0x7f080066
			public const int title_checkbox_1D_barcodes_Code32 = 2131230822;
			
			// aapt resource value: 0x7f080067
			public const int title_checkbox_1D_barcodes_Code39 = 2131230823;
			
			// aapt resource value: 0x7f080069
			public const int title_checkbox_1D_barcodes_Code39Ex = 2131230825;
			
			// aapt resource value: 0x7f08006a
			public const int title_checkbox_1D_barcodes_Code93 = 2131230826;
			
			// aapt resource value: 0x7f08006d
			public const int title_checkbox_1D_barcodes_DHLAWB = 2131230829;
			
			// aapt resource value: 0x7f08006b
			public const int title_checkbox_1D_barcodes_DeutschePostIdentcode = 2131230827;
			
			// aapt resource value: 0x7f08006c
			public const int title_checkbox_1D_barcodes_DeutschePostLeitcode = 2131230828;
			
			// aapt resource value: 0x7f080071
			public const int title_checkbox_1D_barcodes_EAN13 = 2131230833;
			
			// aapt resource value: 0x7f08006f
			public const int title_checkbox_1D_barcodes_EAN8 = 2131230831;
			
			// aapt resource value: 0x7f080073
			public const int title_checkbox_1D_barcodes_FedExGround96 = 2131230835;
			
			// aapt resource value: 0x7f080074
			public const int title_checkbox_1D_barcodes_IATA2of5 = 2131230836;
			
			// aapt resource value: 0x7f080076
			public const int title_checkbox_1D_barcodes_ITF14 = 2131230838;
			
			// aapt resource value: 0x7f080075
			public const int title_checkbox_1D_barcodes_Interleaved2of5 = 2131230837;
			
			// aapt resource value: 0x7f080078
			public const int title_checkbox_1D_barcodes_MSI = 2131230840;
			
			// aapt resource value: 0x7f080077
			public const int title_checkbox_1D_barcodes_Matrix2of5 = 2131230839;
			
			// aapt resource value: 0x7f080079
			public const int title_checkbox_1D_barcodes_NumlyNumber = 2131230841;
			
			// aapt resource value: 0x7f08007a
			public const int title_checkbox_1D_barcodes_OPC = 2131230842;
			
			// aapt resource value: 0x7f08007f
			public const int title_checkbox_1D_barcodes_PZN = 2131230847;
			
			// aapt resource value: 0x7f08007c
			public const int title_checkbox_1D_barcodes_PatchCode = 2131230844;
			
			// aapt resource value: 0x7f08007e
			public const int title_checkbox_1D_barcodes_Pharmacode = 2131230846;
			
			// aapt resource value: 0x7f080081
			public const int title_checkbox_1D_barcodes_RSS14 = 2131230849;
			
			// aapt resource value: 0x7f080083
			public const int title_checkbox_1D_barcodes_RSSExpanded = 2131230851;
			
			// aapt resource value: 0x7f080082
			public const int title_checkbox_1D_barcodes_RSSLimited = 2131230850;
			
			// aapt resource value: 0x7f080086
			public const int title_checkbox_1D_barcodes_SSCC18 = 2131230854;
			
			// aapt resource value: 0x7f080087
			public const int title_checkbox_1D_barcodes_Standard2of5 = 2131230855;
			
			// aapt resource value: 0x7f080089
			public const int title_checkbox_1D_barcodes_SwissPostParcel = 2131230857;
			
			// aapt resource value: 0x7f08008a
			public const int title_checkbox_1D_barcodes_Telepen = 2131230858;
			
			// aapt resource value: 0x7f08008b
			public const int title_checkbox_1D_barcodes_UPCA = 2131230859;
			
			// aapt resource value: 0x7f08008d
			public const int title_checkbox_1D_barcodes_UPCE = 2131230861;
			
			// aapt resource value: 0x7f08008f
			public const int title_checkbox_1D_barcodes_VICS = 2131230863;
			
			// aapt resource value: 0x7f080090
			public const int title_checkbox_1D_barcodes_VIN = 2131230864;
			
			// aapt resource value: 0x7f080048
			public const int title_checkbox_2D_barcodes_Aztec = 2131230792;
			
			// aapt resource value: 0x7f08004a
			public const int title_checkbox_2D_barcodes_DataMatrix = 2131230794;
			
			// aapt resource value: 0x7f08004c
			public const int title_checkbox_2D_barcodes_HanXin = 2131230796;
			
			// aapt resource value: 0x7f080054
			public const int title_checkbox_2D_barcodes_MaxiCode = 2131230804;
			
			// aapt resource value: 0x7f080050
			public const int title_checkbox_2D_barcodes_MicroPDF417 = 2131230800;
			
			// aapt resource value: 0x7f080053
			public const int title_checkbox_2D_barcodes_MicroQR = 2131230803;
			
			// aapt resource value: 0x7f08004d
			public const int title_checkbox_2D_barcodes_PDF417 = 2131230797;
			
			// aapt resource value: 0x7f08004f
			public const int title_checkbox_2D_barcodes_PDF417Compact = 2131230799;
			
			// aapt resource value: 0x7f080051
			public const int title_checkbox_2D_barcodes_QR = 2131230801;
			
			// aapt resource value: 0x7f080056
			public const int title_checkbox_GS1_barcodes_Aztec = 2131230806;
			
			// aapt resource value: 0x7f080057
			public const int title_checkbox_GS1_barcodes_DataMatrix = 2131230807;
			
			// aapt resource value: 0x7f08005b
			public const int title_checkbox_GS1_barcodes_GS1DataBar = 2131230811;
			
			// aapt resource value: 0x7f08005d
			public const int title_checkbox_GS1_barcodes_GS1DataBarExpanded = 2131230813;
			
			// aapt resource value: 0x7f08005f
			public const int title_checkbox_GS1_barcodes_GS1DataBarExpandedStacked = 2131230815;
			
			// aapt resource value: 0x7f08005c
			public const int title_checkbox_GS1_barcodes_GS1DataBarLimited = 2131230812;
			
			// aapt resource value: 0x7f08005e
			public const int title_checkbox_GS1_barcodes_GS1DataBarStacked = 2131230814;
			
			// aapt resource value: 0x7f080059
			public const int title_checkbox_GS1_barcodes_GS1_128 = 2131230809;
			
			// aapt resource value: 0x7f080058
			public const int title_checkbox_GS1_barcodes_QR = 2131230808;
			
			// aapt resource value: 0x7f08002b
			public const int title_checkbox_autofocus = 2131230763;
			
			// aapt resource value: 0x7f08002d
			public const int title_checkbox_autofocus_on_touch = 2131230765;
			
			// aapt resource value: 0x7f08002c
			public const int title_checkbox_continuous_autofocus = 2131230764;
			
			// aapt resource value: 0x7f080036
			public const int title_checkbox_copy_to_clipboard = 2131230774;
			
			// aapt resource value: 0x7f08003d
			public const int title_checkbox_invert_image = 2131230781;
			
			// aapt resource value: 0x7f080093
			public const int title_checkbox_postal_1D_AustralianPost = 2131230867;
			
			// aapt resource value: 0x7f080095
			public const int title_checkbox_postal_1D_DutchKIX = 2131230869;
			
			// aapt resource value: 0x7f08009d
			public const int title_checkbox_postal_1D_IntelligentMail = 2131230877;
			
			// aapt resource value: 0x7f08009f
			public const int title_checkbox_postal_1D_Mailmark4C = 2131230879;
			
			// aapt resource value: 0x7f0800a1
			public const int title_checkbox_postal_1D_Mailmark4L = 2131230881;
			
			// aapt resource value: 0x7f08009b
			public const int title_checkbox_postal_1D_Planet = 2131230875;
			
			// aapt resource value: 0x7f080099
			public const int title_checkbox_postal_1D_Postnet = 2131230873;
			
			// aapt resource value: 0x7f080097
			public const int title_checkbox_postal_1D_RoyalMail = 2131230871;
			
			// aapt resource value: 0x7f08003f
			public const int title_checkbox_reconstruct_structured_append_barcodes = 2131230783;
			
			// aapt resource value: 0x7f080034
			public const int title_checkbox_sound_signal = 2131230772;
			
			// aapt resource value: 0x7f080032
			public const int title_checkbox_stop_scan = 2131230770;
			
			// aapt resource value: 0x7f080035
			public const int title_checkbox_vibration = 2131230773;
			
			// aapt resource value: 0x7f080025
			public const int title_history_empty_message = 2131230757;
			
			// aapt resource value: 0x7f08002e
			public const int title_list_camera_frame_sizes = 2131230766;
			
			// aapt resource value: 0x7f080037
			public const int title_list_encodings = 2131230775;
			
			// aapt resource value: 0x7f080041
			public const int title_list_fps_limit = 2131230785;
			
			// aapt resource value: 0x7f080028
			public const int title_list_languages = 2131230760;
			
			// aapt resource value: 0x7f08003a
			public const int title_list_recognition_mode = 2131230778;
			
			// aapt resource value: 0x7f080045
			public const int title_set_default_settings = 2131230789;
			
			// aapt resource value: 0x7f080027
			public const int unsupported_encoding_message = 2131230759;
			
			// aapt resource value: 0x7f08001a
			public const int upce_value_message = 2131230746;
			
			// aapt resource value: 0x7f080005
			public const int vintasoft_barcodes_url = 2131230725;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int settings_page = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
